##### Where is the data? #####

fast5_path: path/to/fast5
basecalled_path: path/to/data
annotated_path: annotations
output_path: analysis 


##### Mapping reference panel #####

references_file: ../../references.fasta


##### Read length filtering range #####

min_read_length: 250
max_read_length: 500


##### Barcodes to process #####
