##### Where is the data? #####

fast5_path: path/to/fast5
basecalled_path: path/to/data
annotated_path: annotations


##### Read length filtering range #####

min_read_length: 370
max_read_length: 700


##### Barcodes to process #####
